Claim get all open and update status
Five-Fishes/Club-Management-Spring-Server pull request #98
Opened 2021-04-09 05:47 UTC by CarlosSia

Resolve #67 
Resolve #68

2021-04-09 13:13 UTC, kachun333 requested changes, later dismissed

2021-04-09 13:13 UTC, kachun333 commented on src/main/java/com/thirdcc/webapp/web/rest/ClaimResource.java
> +    @PreAuthorize("hasRole(\"" + AuthoritiesConstants.ADMIN + "\") || @managementTeamSecurityExpression.isCurrentAdministrator()")
please don't use `hasRole(\"" + AuthoritiesConstants.ADMIN + "\")` anymore
use `managementTeamSecurityExpression` instead

2021-04-09 13:13 UTC, kachun333 commented on src/main/java/com/thirdcc/webapp/web/rest/ClaimResource.java
> +    @PreAuthorize("hasRole(\"" + AuthoritiesConstants.ADMIN + "\") || @managementTeamSecurityExpression.isCurrentAdministrator()")
same issue. don't use `"hasRole(\"" + AuthoritiesConstants.ADMIN + "\")`

2021-04-12 12:44 UTC, CarlosSia commented on src/main/java/com/thirdcc/webapp/web/rest/ClaimResource.java
> +    @PreAuthorize("hasRole(\"" + AuthoritiesConstants.ADMIN + "\") || @managementTeamSecurityExpression.isCurrentAdministrator()")
Resolve by https://github.com/Five-Fishes/Club-Management-Spring-Server/pull/98/commits/fe3e1946a1a7d5606072eb3fc2df3efbff6a8015

2021-04-12 12:44 UTC, CarlosSia commented on src/main/java/com/thirdcc/webapp/web/rest/ClaimResource.java
> +    @PreAuthorize("hasRole(\"" + AuthoritiesConstants.ADMIN + "\") || @managementTeamSecurityExpression.isCurrentAdministrator()")
Resolved by https://github.com/Five-Fishes/Club-Management-Spring-Server/pull/98/commits/fe3e1946a1a7d5606072eb3fc2df3efbff6a8015

2021-04-14 05:36 UTC, LUXIANZE approved these changes

2021-04-14 13:16 UTC, HowardYaw approved these changes

2021-04-14 13:17 UTC, merged